// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by "ffi-gen".
/* tslint:disable */
/* eslint:disable */

/**
 * Main entry point to the library.
 */
export class Api {
  /**
   * API constructor.
   *
   * @returns an `Api` instance.
   */
  constructor();

  /**
   * Initialize the API.
   *
   * @returns a promise resolved when initialization is done.
   */
  fetch(url, imports): Promise<void>;

  /**
   * Prints a friendly greeting to stdout.
   */
  helloWorld(): void;

  /**
   * Returns a future that prints a friendly
   * greeting to stdout.
   */
  asyncHelloWorld(): Promise<number>;
}
