use crate::{Abi, AbiFunction, AbiType, Interface, PrimType};
use genco::prelude::*;
use genco::tokens::static_literal;

pub struct DartGenerator {
    abi: Abi,
    cdylib_name: String,
}

impl DartGenerator {
    pub fn new(cdylib_name: String) -> Self {
        Self {
            abi: Abi::native(),
            cdylib_name,
        }
    }

    pub fn generate(&self, iface: Interface) -> dart::Tokens {
        quote! {
            #(static_literal("//")) AUTO GENERATED FILE, DO NOT EDIT.
            #(static_literal("//"))
            #(static_literal("//")) Generated by "ffi-gen".

            import "dart:convert";
            import "dart:ffi" as ffi;
            import "dart:io" show Platform;
            import "dart:typed_data";

            class _Slice extends ffi.Struct {
                external ffi.Pointer<ffi.Uint8> ptr;

                @ffi.IntPtr()
                external int len;
            }

            class _Alloc extends ffi.Struct {
                external ffi.Pointer<ffi.Uint8> ptr;

                @ffi.IntPtr()
                external int len;

                @ffi.IntPtr()
                external int cap;
            }

            ffi.Pointer<ffi.Void> _registerFinalizer(Box boxed) {
                final dart = ffi.DynamicLibrary.executable();
                final registerPtr = dart.lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(
                    ffi.Handle, ffi.Pointer<ffi.Void>, ffi.IntPtr, ffi.Pointer<ffi.Void>)>>("Dart_NewFinalizableHandle");
                final register = registerPtr
                    .asFunction<ffi.Pointer<ffi.Void> Function(
                        Object, ffi.Pointer<ffi.Void>, int, ffi.Pointer<ffi.Void>)>();
                return register(boxed, boxed._ptr, 42, boxed._dropPtr.cast());
            }

            void _unregisterFinalizer(Box boxed) {
                final dart = ffi.DynamicLibrary.executable();
                final unregisterPtr = dart.lookup<ffi.NativeFunction<ffi.Void Function(
                    ffi.Pointer<ffi.Void>, ffi.Handle)>>("Dart_DeleteFinalizableHandle");
                final unregister = unregisterPtr
                    .asFunction<void Function(ffi.Pointer<ffi.Void>, Box)>();
                unregister(boxed._finalizer, boxed);
            }

            class Box {
                final Api _api;
                final ffi.Pointer<ffi.Void> _ptr;
                final String _drop_symbol;
                bool _dropped;
                bool _moved;
                ffi.Pointer<ffi.Void> _finalizer = ffi.Pointer.fromAddress(0);

                Box(this._api, this._ptr, this._drop_symbol) : _dropped = false, _moved = false;

                late final _dropPtr = this._api._lookup<
                    ffi.NativeFunction<
                        ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)>>(this._drop_symbol);

                late final _drop = _dropPtr.asFunction<
                    void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)>();

                ffi.Pointer<ffi.Void> borrow() {
                    if (this._dropped) {
                        throw new StateError("use after free");
                    }
                    if (this._moved) {
                        throw new StateError("use after move");
                    }
                    return this._ptr;
                }

                ffi.Pointer<ffi.Void> move() {
                    if (this._dropped) {
                        throw new StateError("use after free");
                    }
                    if (this._moved) {
                        throw new StateError("can't move value twice");
                    }
                    this._moved = true;
                    _unregisterFinalizer(this);
                    return this._ptr;
                }

                void drop() {
                    if (this._dropped) {
                        throw new StateError("double free");
                    }
                    if (this._moved) {
                        throw new StateError("can't drop moved value");
                    }
                    this._dropped = true;
                    _unregisterFinalizer(this);
                    this._drop(ffi.Pointer.fromAddress(0), this._ptr);
                }
            }

            class Api {
                #(static_literal("///")) Holds the symbol lookup function.
                final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
                    _lookup;

                #(static_literal("///")) The symbols are looked up in [dynamicLibrary].
                Api(ffi.DynamicLibrary dynamicLibrary)
                    : _lookup = dynamicLibrary.lookup;

                #(static_literal("///")) The symbols are looked up with [lookup].
                Api.fromLookup(
                    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
                        lookup)
                    : _lookup = lookup;

                #(static_literal("///")) The library is loaded from the executable.
                factory Api.loadStatic() {
                    return Api(ffi.DynamicLibrary.executable());
                }

                #(static_literal("///")) The library is dynamically loaded.
                factory Api.loadDynamic(String name) {
                    return Api(ffi.DynamicLibrary.open(name));
                }

                #(static_literal("///")) The library is loaded based on platform conventions.
                factory Api.load() {
                    String? name;
                    if (Platform.isLinux) name = #_(#("lib")#(&self.cdylib_name)#(".so"));
                    if (Platform.isAndroid) name = #_(#("lib")#(&self.cdylib_name)#(".so"));
                    if (Platform.isMacOS) name = #_(#("lib")#(&self.cdylib_name)#(".dylib"));
                    if (Platform.isIOS) name = #_("");
                    if (Platform.isWindows) #_(#(&self.cdylib_name)#(".dll"));
                    if (name == null) {
                        throw UnsupportedError(#_("This platform is not supported."));
                    }
                    if (name == "") {
                        return Api.loadStatic();
                    } else {
                        return Api.loadDynamic(name);
                    }
                }

                late final _allocatePtr = _lookup<
                    ffi.NativeFunction<
                        ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr, ffi.IntPtr)>>("allocate");

                late final _allocate = _allocatePtr.asFunction<
                    ffi.Pointer<ffi.Uint8> Function(int, int)>();

                ffi.Pointer<T> allocate<T extends ffi.NativeType>(int byteCount, int alignment) {
                    return _allocate(byteCount, alignment).cast();
                }

                late final _deallocatePtr = _lookup<
                    ffi.NativeFunction<
                        ffi.Void Function(ffi.Pointer<ffi.Uint8>, ffi.IntPtr, ffi.IntPtr)>>("deallocate");

                late final _deallocate = _deallocatePtr.asFunction<
                    Function(ffi.Pointer<ffi.Uint8>, int, int)>();

                void deallocate<T extends ffi.NativeType>(ffi.Pointer pointer, int byteCount, int alignment) {
                    this._deallocate(pointer.cast(), byteCount, alignment);
                }

                #(for func in iface.into_functions() => #(self.generate_function(func)))
            }
        }
    }

    fn generate_function(&self, func: AbiFunction) -> dart::Tokens {
        quote! {
            #(self.generate_return(func.ret.as_ref())) #(&func.name)(
                #(for (name, ty) in &func.args => #(self.generate_arg(name, ty))))
            {
                #(for (name, ty) in &func.args => #(self.generate_lower(name, ty)))
                final ret = #(format!("_{}", &func.name))(
                    #(for (name, ty) in &func.args => #(self.generate_lower_args(name, ty))));
                #(self.generate_lift(func.ret.as_ref()))
                #(for (name, ty) in &func.args => #(self.generate_lower_cleanup(name, ty)))
                #(self.generate_return_stmt(func.ret.as_ref()))
            }

            late final #(format!("_{}Ptr", &func.name)) = _lookup<
                ffi.NativeFunction<
                    #(self.generate_return_native(func.ret.as_ref()))
                        Function(#(for (name, ty) in &func.args => #(self.generate_arg_native(name, ty))))>>(
                            #_(#(format!("__{}", &func.name))));

            late final #(format!("_{}", &func.name)) = #(format!("_{}Ptr", &func.name))
                .asFunction<#(self.generate_return_wrapped(func.ret.as_ref()))
                    Function(#(for (name, ty) in &func.args => #(self.generate_arg_wrapped(name, ty))))>();
        }
    }

    fn generate_arg(&self, name: &str, ty: &AbiType) -> dart::Tokens {
        match ty {
            AbiType::Prim(ty) => quote!(#(self.generate_prim_type(*ty)) #name,),
            AbiType::RefStr | AbiType::String => quote!(String #name,),
            AbiType::RefSlice(ty) | AbiType::Vec(ty) => {
                quote!(List<#(self.generate_prim_type(*ty))> #name,)
            }
            AbiType::Box(_) | AbiType::Ref(_) => quote!(Box #name,),
        }
    }

    fn generate_arg_native(&self, _name: &str, ty: &AbiType) -> dart::Tokens {
        match ty {
            AbiType::Prim(ty) => quote!(#(self.generate_prim_type_native(*ty)),),
            AbiType::RefStr => quote!(ffi.Pointer<ffi.Uint8>, ffi.IntPtr,),
            AbiType::RefSlice(ty) => {
                quote!(ffi.Pointer<#(self.generate_prim_type_native(*ty))>, ffi.IntPtr,)
            }
            AbiType::String => {
                quote!(ffi.Pointer<ffi.Uint8>, ffi.IntPtr, ffi.IntPtr)
            }
            AbiType::Vec(ty) => {
                quote!(ffi.Pointer<#(self.generate_prim_type_native(*ty))>, ffi.IntPtr, ffi.IntPtr,)
            }
            AbiType::Box(_) | AbiType::Ref(_) => quote!(ffi.Pointer<ffi.Void>,),
        }
    }

    fn generate_arg_wrapped(&self, _name: &str, ty: &AbiType) -> dart::Tokens {
        match ty {
            AbiType::Prim(ty) => quote!(#(self.generate_prim_type_wrapped(*ty)),),
            AbiType::RefStr => quote!(ffi.Pointer<ffi.Uint8>, int,),
            AbiType::String => quote!(ffi.Pointer<ffi.Uint8>, int, int,),
            AbiType::RefSlice(ty) => {
                quote!(ffi.Pointer<#(self.generate_prim_type_native(*ty))>, int,)
            }
            AbiType::Vec(ty) => {
                quote!(ffi.Pointer<#(self.generate_prim_type_native(*ty))>, int, int,)
            }
            AbiType::Box(_) | AbiType::Ref(_) => quote!(ffi.Pointer<ffi.Void>,),
        }
    }

    fn generate_lower(&self, name: &str, ty: &AbiType) -> dart::Tokens {
        match ty {
            AbiType::Prim(PrimType::Bool) => quote!(final int #(name)_int = #name ? 1 : 0;),
            AbiType::Prim(_) => quote!(),
            AbiType::RefStr | AbiType::String => quote! {
                final #(name)_utf8 = utf8.encode(#(name));
                final int #(name)_len = #(name)_utf8.length;
                final ffi.Pointer<ffi.Uint8> #(name)_ptr = this.allocate(#(name)_len, 1);
                final Uint8List #(name)_view = #(name)_ptr.asTypedList(#(name)_len);
                #(name)_view.setAll(0, #(name)_utf8);
            },
            AbiType::RefSlice(ty) | AbiType::Vec(ty) => {
                let (size, align) = self.abi.layout(*ty);
                quote! {
                    final int #(name)_len = #(name).length;
                    final ffi.Pointer<#(self.generate_prim_type_native(*ty))> #(name)_ptr =
                        this.allocate(#(name)_len * #size, #align);
                    final #(name)_view = #(name)_ptr.asTypedList(#(name)_len);
                    #(name)_view.setAll(0, #(name));
                }
            }
            AbiType::Box(_) => quote!(final #(name)_ptr = #(name).move();),
            AbiType::Ref(_) => quote!(final #(name)_ptr = #(name).borrow();),
        }
    }

    fn generate_lower_args(&self, name: &str, ty: &AbiType) -> dart::Tokens {
        match ty {
            AbiType::Prim(PrimType::Bool) => quote!(#(name)_int,),
            AbiType::Prim(_) => quote!(#(name)),
            AbiType::RefStr | AbiType::RefSlice(_) => quote!(#(name)_ptr, #(name)_len,),
            AbiType::String | AbiType::Vec(_) => quote!(#(name)_ptr, #(name)_len, #(name)_len,),
            AbiType::Box(_) | AbiType::Ref(_) => quote!(#(name)_ptr,),
        }
    }

    fn generate_lower_cleanup(&self, name: &str, ty: &AbiType) -> dart::Tokens {
        match ty {
            AbiType::Prim(_) => quote!(),
            AbiType::RefStr | AbiType::RefSlice(_) => {
                quote!(this.deallocate(#(name)_ptr, #(name)_len, 1);)
            }
            AbiType::String | AbiType::Vec(_) => quote!(),
            AbiType::Box(_) | AbiType::Ref(_) => quote!(),
        }
    }

    fn generate_lift(&self, ret: Option<&AbiType>) -> dart::Tokens {
        if let Some(ret) = ret {
            match ret {
                AbiType::Prim(PrimType::Bool) => quote!(final ret_bool = ret > 0;),
                AbiType::Prim(_) => quote!(),
                AbiType::RefStr => quote! {
                    final ret_str = utf8.decode(ret.ptr.asTypedList(ret.len));
                },
                AbiType::RefSlice(_) => quote! {
                    final ret_list = ret.ptr.asTypedList(ret.len).toList();
                },
                AbiType::String => quote! {
                    final ret_str = utf8.decode(ret.ptr.asTypedList(ret.len));
                    if (ret.cap > 0) {
                        this.deallocate(ret.ptr, ret.cap, 1);
                    }
                },
                AbiType::Vec(ty) => {
                    let (size, align) = self.abi.layout(*ty);
                    quote! {
                        final ffi.Pointer<#(self.generate_prim_type_native(*ty))> ret_list_ptr = ret.ptr.cast();
                        final ret_list = ret_list_ptr.asTypedList(ret.len).toList();
                        if (ret.cap > 0) {
                            this.deallocate(ret.ptr, ret.cap * #size, #align);
                        }
                    }
                }
                AbiType::Box(ident) => {
                    let destructor = format!("drop_box_{}", ident);
                    quote! {
                        final ret_box = new Box(this, ret, #_(#destructor));
                        ret_box._finalizer = _registerFinalizer(ret_box);
                    }
                }
                AbiType::Ref(_) => unreachable!(),
            }
        } else {
            quote!()
        }
    }

    fn generate_return_stmt(&self, ret: Option<&AbiType>) -> dart::Tokens {
        if let Some(ret) = ret {
            match ret {
                AbiType::Prim(PrimType::Bool) => quote!(return ret_bool;),
                AbiType::Prim(_) => quote!(return ret;),
                AbiType::RefStr | AbiType::String => quote!(return ret_str;),
                AbiType::RefSlice(_) | AbiType::Vec(_) => quote!(return ret_list;),
                AbiType::Box(_) | AbiType::Ref(_) => quote!(return ret_box;),
            }
        } else {
            quote!()
        }
    }

    fn generate_return(&self, ret: Option<&AbiType>) -> dart::Tokens {
        if let Some(ret) = ret {
            match ret {
                AbiType::Prim(ty) => self.generate_prim_type(*ty),
                AbiType::RefStr | AbiType::String => quote!(String),
                AbiType::RefSlice(ty) | AbiType::Vec(ty) => {
                    quote!(List<#(self.generate_prim_type(*ty))>)
                }
                AbiType::Box(_) => quote!(Box),
                AbiType::Ref(ident) => panic!("invalid return type `&{}`", ident),
            }
        } else {
            quote!(void)
        }
    }

    fn generate_return_native(&self, ret: Option<&AbiType>) -> dart::Tokens {
        if let Some(ret) = ret {
            match ret {
                AbiType::Prim(ty) => self.generate_prim_type_native(*ty),
                AbiType::RefStr | AbiType::RefSlice(_) => quote!(_Slice),
                AbiType::String | AbiType::Vec(_) => quote!(_Alloc),
                AbiType::Box(_) => quote!(ffi.Pointer<ffi.Void>),
                AbiType::Ref(_) => unreachable!(),
            }
        } else {
            quote!(ffi.Void)
        }
    }

    fn generate_return_wrapped(&self, ret: Option<&AbiType>) -> dart::Tokens {
        if let Some(ret) = ret {
            match ret {
                AbiType::Prim(ty) => self.generate_prim_type_wrapped(*ty),
                AbiType::RefStr | AbiType::RefSlice(_) => quote!(_Slice),
                AbiType::String | AbiType::Vec(_) => quote!(_Alloc),
                AbiType::Box(_) => quote!(ffi.Pointer<ffi.Void>),
                AbiType::Ref(_) => unreachable!(),
            }
        } else {
            quote!(void)
        }
    }

    fn generate_prim_type_native(&self, ty: PrimType) -> dart::Tokens {
        match ty {
            PrimType::U8 => quote!(ffi.Uint8),
            PrimType::U16 => quote!(ffi.Uint16),
            PrimType::U32 => quote!(ffi.Uint32),
            PrimType::U64 => quote!(ffi.Uint64),
            PrimType::Usize => match self.abi.ptr_width() {
                32 => quote!(ffi.Uint32),
                64 => quote!(ffi.Uint64),
                _ => unimplemented!(),
            },
            PrimType::I8 => quote!(ffi.Int8),
            PrimType::I16 => quote!(ffi.Int16),
            PrimType::I32 => quote!(ffi.Int32),
            PrimType::I64 => quote!(ffi.Int64),
            PrimType::Isize => match self.abi.ptr_width() {
                32 => quote!(ffi.Uint32),
                64 => quote!(ffi.Uint64),
                _ => unimplemented!(),
            },
            PrimType::Bool => quote!(ffi.Uint8),
            PrimType::F32 => quote!(ffi.Float),
            PrimType::F64 => quote!(ffi.Double),
        }
    }

    fn generate_prim_type_wrapped(&self, ty: PrimType) -> dart::Tokens {
        match ty {
            PrimType::U8
            | PrimType::U16
            | PrimType::U32
            | PrimType::U64
            | PrimType::Usize
            | PrimType::I8
            | PrimType::I16
            | PrimType::I32
            | PrimType::I64
            | PrimType::Isize
            | PrimType::Bool => quote!(int),
            PrimType::F32 | PrimType::F64 => quote!(double),
        }
    }

    fn generate_prim_type(&self, ty: PrimType) -> dart::Tokens {
        match ty {
            PrimType::U8
            | PrimType::U16
            | PrimType::U32
            | PrimType::U64
            | PrimType::Usize
            | PrimType::I8
            | PrimType::I16
            | PrimType::I32
            | PrimType::I64
            | PrimType::Isize => quote!(int),
            PrimType::Bool => quote!(bool),
            PrimType::F32 | PrimType::F64 => quote!(double),
        }
    }
}

#[cfg(feature = "test_runner")]
pub mod test_runner {
    use super::*;
    use crate::{Abi, RustGenerator};
    use anyhow::Result;
    use std::io::Write;
    use tempfile::NamedTempFile;
    use trybuild::TestCases;

    pub fn compile_pass(iface: &str, rust: rust::Tokens, dart: dart::Tokens) -> Result<()> {
        let iface = Interface::parse(iface)?;
        let mut rust_file = NamedTempFile::new()?;
        let mut rust_gen = RustGenerator::new(Abi::native());
        let rust_tokens = rust_gen.generate(iface.clone());
        let mut dart_file = NamedTempFile::new()?;
        let dart_gen = DartGenerator::new("compile_pass".to_string());
        let dart_tokens = dart_gen.generate(iface);

        let library_tokens = quote! {
            #rust_tokens
            #rust
        };

        let bin_tokens = quote! {
            #dart_tokens

            extension on List {
                bool equals(List list) {
                    if (this.length != list.length) return false;
                    for (int i = 0; i < this.length; i++) {
                        if (this[i] != list[i]) {
                            return false;
                        }
                    }
                    return true;
                }
            }

            void main() {
                final api = Api.load();
                #dart
            }
        };

        let library = library_tokens.to_file_string()?;
        rust_file.write_all(library.as_bytes())?;
        let bin = bin_tokens.to_file_string()?;
        dart_file.write_all(bin.as_bytes())?;

        let library_dir = tempfile::tempdir()?;
        let library_file = library_dir.as_ref().join("libcompile_pass.so");
        let runner_tokens: rust::Tokens = quote! {
            fn main() {
                use std::process::Command;
                let ret = Command::new("rustc")
                    .arg("--crate-name")
                    .arg("compile_pass")
                    .arg("--crate-type")
                    .arg("cdylib")
                    .arg("-o")
                    .arg(#(quoted(library_file.as_path().to_str().unwrap())))
                    .arg(#(quoted(rust_file.as_ref().to_str().unwrap())))
                    .status()
                    .unwrap()
                    .success();
                assert!(ret);
                let ret = Command::new("dart")
                    .env("LD_LIBRARY_PATH", #(quoted(library_dir.as_ref().to_str().unwrap())))
                    .arg("--enable-asserts")
                    //.arg("--observe")
                    //.arg("--write-service-info=service.json")
                    .arg(#(quoted(dart_file.as_ref().to_str().unwrap())))
                    .status()
                    .unwrap()
                    .success();
                assert!(ret);
            }
        };

        let mut runner_file = NamedTempFile::new()?;
        let runner = runner_tokens.to_file_string()?;
        runner_file.write_all(runner.as_bytes())?;

        let test = TestCases::new();
        test.pass(runner_file.as_ref());
        Ok(())
    }
}
